/*----- PROTECTED REGION ID(Monitor.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Monitor.cpp
//
// description : C++ source for the Monitor class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Monitor are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Monitor.h>
#include <MonitorClass.h>

/*----- PROTECTED REGION END -----*/	//	Monitor.cpp

/**
 *  Monitor class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  Count  |  Tango::DevULong	Scalar
//================================================================

namespace Monitor_ns
{
/*----- PROTECTED REGION ID(Monitor::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Monitor::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Monitor::Monitor()
 *	Description : Constructors for a Tango device
 *                implementing the classMonitor
 */
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Monitor::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_1
}
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(Monitor::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_2
}
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(Monitor::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Monitor::delete_device()
{
	DEBUG_STREAM << "Monitor::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::delete_device
	delete[] attr_Count_read;
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Monitor::init_device()
{
	DEBUG_STREAM << "Monitor::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::init_device_before
	
	//	No device property to be read from database
	
	attr_Count_read = new Tango::DevULong[1];
	/*----- PROTECTED REGION ID(Monitor::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::init_device
}


//--------------------------------------------------------
/**
 *	Method      : Monitor::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Monitor::always_executed_hook()
{
	DEBUG_STREAM << "Monitor::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Monitor::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Monitor::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Count related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Monitor::read_Count(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Monitor::read_Count(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::read_Count) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Count_read);
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::read_Count
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Monitor::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Monitor::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void Monitor::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(Monitor::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::add_dynamic_commands
}

/*----- PROTECTED REGION ID(Monitor::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Monitor::namespace_ending
} //	namespace
